from . import res_company
from . import res_config_settings
from . import hr_shift_template
from . import hr_shift_assignment
from . import shift_dashboard
from . import hr_shift_change_request
from . import hr_contract
from . import hr_employee
from . import hr_attendance
from . import hr_leave
from . import hr_work_entry
